insert into produtos values (default, 'Açucar refinado', 4.99, 1, 1, 1000, default, default);
insert into produtos values (default, 'Feijão carioca', 7.89, 1, 1, 1000, default, default);
insert into produtos values (default, 'Café Pilão', 112.99, 3, 5, 2500, default, default);
insert into produtos values (default, 'Arroz Agulhinha', 22.69, 1, 1, 5000, default, default);
insert into produtos values (default, 'Macarrão Italiano Parafuso', 37.99, 2, 3, 500, default, default);
insert into produtos values (default, 'Kit Café Melita', 47.99, 3, 2, 1000, default, default);
insert into produtos values (default, 'Macarrão Italiano Fusilli', 17.99, 1, 1, 500, default, default);
insert into produtos values (default, 'Mix de Sementes', 50.99, 3, 5, 250, default, default);
insert into produtos values (default, 'Café Solúvel', 47.99, 3, 2, 250, default, default);
insert into produtos values (default, 'Polvilho Azedo Yoki', 12.79, 1, 1, 500, default, default);
insert into produtos values (default, 'Arroz Polido', 37.79, 3, 3, 15000, default, default);
insert into produtos values (default, 'Barra de chocolate Nestle', 17.79, 3, 3, 900, default, default);
insert into produtos values (default, 'Chia em grãos', 82.29, 2, 5, 600, default, default);
insert into produtos values (default, 'Café em capsulas', 160.59, 2, 10, 500, default, default);
insert into produtos values(default, 'Macarrão integral', 22.80, 2, 5, 2500, default, default);
insert into produtos values (default, 'Aveia em flocos', 42.89, 1, 1, 200, default, default);
insert into produtos values (default, 'Farinha de trigo', 12.89, 1, 1, 1000, default, default);